apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: api-gateway
    image: api-gateway:1.0
    ports:
      - containerPort: 8080
    imagePullPolicy: Never
    resources:
      requests: {}
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30048
