apiVersion: v1
kind: Pod
metadata:
  name: car-service
  labels:
    app: car-service
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: carservice
    image: car-service:1.0
    ports:
      - containerPort: 8090
    imagePullPolicy: Never
    resources:
      requests: {}
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: car-service
  labels:
    app: car-service
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: car-service
  ports:
  - name: tcp
    port: 8090
    targetPort: 8090
    nodePort: 30050
